Update rsa

diff --git a/rsa b/rsa
--- a/rsa
+++ b/rsa
@@ -1,25 +1,19 @@
 #!/usr/bin/env bash
-#challange
-check_factor() {
-    if [ $# -ne 1 ]; then
-        echo "Usage: check_factor <number>"
-        exit 1
-    fi
-
-    num=$1
-    result=$(factor "$num")
-
-    # Extract the prime factors from the result
-    prime_factors=$(echo "$result" | awk '{print $2, $3}')
-
-    echo "Prime factors: $prime_factors"
-}
 
 if [ $# -ne 1 ]; then
     echo 'Usage: rsa <file>'
     exit 1
-else
-    while read -r i; do
-        check_factor "$i"
-    done < "$1"
 fi
+
+file="$1"
+if [ ! -f "$file" ]; then
+    echo "File '$file' not found."
+    exit 1
+fi
+
+# Read the number from the file
+read -r number < "$file"
+
+prime_factors=$(factor "$number" | awk '{print $2}' | tac | paste -sd '*')
+echo "$number = $prime_factors"
+
